name: Auto Create Pull Request

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run update script
        run: python update_data.py

      - name: Configure Git
        run: |
          git config --global user.name "AutoBot"
          git config --global user.email "autobot@example.com"

      - name: Create new branch
        run: |
          git checkout -b auto-update-data || git checkout auto-update-data
          git add Data.csv
          git commit -m "Auto-update Data.csv" || echo "No changes to commit"
          git push -u origin auto-update-data

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_PAT }}
          commit-message: Auto-update Data.csv
          branch: auto-update-data
          title: "Daily Data Update"
          body: "This PR updates Data.csv with the latest data."
          base: main
