name: Auto Commit Data.csv

on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6:00 AM IST
  workflow_dispatch:     # Allows manual trigger

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest

    env:
      SMARTAPI_CLIENT_ID: ${{ secrets.SMARTAPI_CLIENT_ID }}
      SMARTAPI_API_KEY: ${{ secrets.SMARTAPI_API_KEY }}
      SMARTAPI_MPIN: ${{ secrets.SMARTAPI_MPIN }}
      SMARTAPI_SECRET_KEY: ${{ secrets.SMARTAPI_SECRET_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run update script
        run: python update_data.py

      - name: Configure Git
        run: |
          git config --global user.name "AutoBot"
          git config --global user.email "autobot@example.com"

      - name: Commit changes
        run: |
          git add Data.csv
          git commit -m "Auto-update Data.csv" || echo "No changes to commit"

      - name: Push changes using PAT
        env:
          TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git push origin main
