name: Update Data Daily

on:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 3 AM UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install yfinance pandas

      - name: Run update script
        run: python update_data.py

      - name: Commit and push changes
        run: |
          git config --global user.name "AutoBot"
          git config --global user.email "autobot@example.com"
          git add .
          git commit -m "Auto-update Data.csv" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/kur2022/kumarrathod.git
          git push origin main
