name: Update Data Daily

on:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 3 AM UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install yfinance pandas

      - name: Run update script
        run: python update_data.py

      - name: Commit updated CSV
        run: |
          git config --global user.name 'AutoBot'
          git config --global user.email 'kumar.rathod85@gmail.com.com'
          git add Data.csv
          git commit -m "Auto-update Data.csv"
          git push
